[package]
name = "nodpirust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
tokio = { version = "1.36", features = ["full"] }
chrono = "0.4"

# [target.'cfg(windows)'.dependencies]
# winreg = "0.52"
